const { v4: uuidv4 } = require("uuid");

const stripe = require("stripe")(
  "sk_test_51IlZycKBsFdldFb4DFJHVTKxKo0ZmaXBM1IvIGFgUBaYnsIx3MS5l9B8Z34a8qohlzMhUtXBfqyHKZsYSPf43bg000GpJbMLJj",
);

const payment = async (req, res, next) => {
  const { email, product, authToken } = req.body;
  console.log("########### req body ############", req.body);
  console.log("************************* PRODUCT ", product);
  const { token } = authToken;
  const { card } = token;
  console.log("111111111", card);
  console.log(
    "============================================== payment initiate =======================",
  );
  // const userProduct = {

  // };
  // unique ID generated by client
  const idempotencyKey = uuidv4();
  try {
    const customer = await stripe.customers.create({
      email: email,
      source: token.id,
    });
    console.log("Customer Created.....");
    console.log(customer);
    const response = await stripe.charges.create(
      {
        amount: product.amount * 100,
        currency: "INR",
        customer: customer.id,
        receipt_email: email,
        description: product.description,
        shipping: {
          name: card.name,
          address: {
            line1: "MAHDIA",
            country: card.address_country,
          },
        },
      },
      { idempotencyKey: idempotencyKey },
    );
    console.log("charge response");
    console.log(response);
    res.json(response);
  } catch (err) {
    console.log(
      "=========================================== error ==========================",
    );
    console.log(err);
    res.json(err);
  }
};

module.exports = {
  payment,
};
